server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:flight_reservation.db
    driver-class-name: org.sqlite.JDBC
  
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m

logging:
  level:
    com.flight.reservation: DEBUG
    org.springframework.cache: DEBUG